spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/autoloader_dispatch
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  spring-doc:
    api-docs:
      enabled: true
      swagger-ui:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true

logging:
  level:
    root: INFO
    ru.autoloader: DEBUG