spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/autoloader_dispatch
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/autoloader_dispatch
    user: postgres
    password: mypassword